CREATE TABLE PIRSON (
    FIRST_NAME VARCHAR2(15) NOT NULL,
    LAST_NAME VARCHAR2(15) NOT NULL,
    SYS_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
    GOV_ID VARCHAR2(9) UNIQUE NOT NULL,
    AGE INTEGER,
    USER_NAME VARCHAR2(15) UNIQUE NOT NULL,
    PASSWORD_ VARCHAR2(15) NOT NULL
);