CREATE TABLE PIRSON (
    FIRST_NAME VARCHAR2(15) NOT NULL,
    LAST_NAME VARCHAR2(15) NOT NULL,
    SYS_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
    GOV_ID VARCHAR2(9) UNIQUE NOT NULL,
    AGE INTEGER,
    USER_NAME VARCHAR2(15) UNIQUE NOT NULL,
    PASSWORD_ VARCHAR2(15) NOT NULL
);
CREATE TABLE TRIP (
    TRIP_ID VARCHAR2(15) PRIMARY KEY,
    DATE_ DATE NOT NULL,
    PRICE INTEGER NOT NULL,
    TRIP_LOCATION VARCHAR2(15) NOT NULL,
    TRIP_HOTEL VARCHAR2(15),
    TRANSPORTATION_WAY VARCHAR2(15) NOT NULL,
    TRIP_PATH_DESCRIPTION VARCHAR2(300) NOT NULL
);
CREATE TABLE HOTEL (
    HOTEL_ID VARCHAR2(15) PRIMARY KEY,
    HOTEL_NAME VARCHAR2(15) NOT NULL,
    HOTEL_STARS INTEGER NOT NULL,
    LOCATION_ID VARCHAR2(15)
);
CREATE TABLE ROOM_KINDS (
    HOTEL_ID VARCHAR2(15),
    ROOM_KIND VARCHAR2(15)
);
CREATE TABLE LOCATIONS (
    LOCATION_ID VARCHAR2(15) PRIMARY KET,
    REQUIRED_DECUMENTS VARCHAR2(300),
    CONTRY VARCHAR2(20) NOT NULL,
    CITY VARCHAR2(15) NOT NULL
)
CREATE TABLE TRANSPORTATION_WAYS (
    LOCATION_ID VARCHAR2(15),
    TRANSPORTATION_WAY VARCHAR2(15)
);